language: c
dist: trusty
sudo: required
install:
  - sudo apt-get update
  - sudo apt-get -y install
        libclang-3.8-dev
        python-clang-3.8
        python-pip
  - sudo /usr/bin/pip install
        astroid==1.4.8
        isort==3.9.0
        pylint==1.6.4
script:
  - PATH=/usr/bin:$PATH make check
